version: '3.7'

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    user: "1001:1001"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE  # Optional, for loading WireGuard kernel module if not present
    environment:
      - PUID=1001  # Make sure this matches the user ID on the host
      - PGID=1001  # Make sure this matches the group ID on the host
      - TZ=Europe/Paris  # Set your timezone (replace if needed)
      - SERVERPORT=51820  # WireGuard port (default is 51820)
      - INTERNAL_SUBNET=fd00:abcd:1234::/64  # Set your internal IPv6 subnet
      - ALLOWEDIPS=fd00:abcd:1234::/64  # Only allow access to this IPv6 subnet
      - LOG_CONFS=true  # Enable configuration logs (optional)
    volumes:
      - /etc/wireguard:/config  # Path to store WireGuard config on the host
      - /lib/modules:/lib/modules  # Optional, for kernel modules if required
    ports:
      - 51820:51820/udp  # Expose the WireGuard port (51820 UDP by default)
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1  # Needed for proper routing with WireGuard
    restart: unless-stopped
