---
- name: Top 10 Hardening Checks
  hosts: all
  gather_facts: false
  tasks:

    - name: Check 1 - Ensure password expiration is set
      shell: |
        grep -E '^PASS_MAX_DAYS' /etc/login.defs || echo "PASS_MAX_DAYS 99999"
      register: pass_max_days
      changed_when: false

    - name: Check 2 - Ensure SSH root login is disabled
      shell: |
        grep -E '^PermitRootLogin no' /etc/ssh/sshd_config || echo "PermitRootLogin no"
      register: ssh_root_login
      changed_when: false

    - name: Check 3 - Ensure firewall is enabled
      shell: |
        systemctl is-active ufw || echo "ufw not active"
      register: firewall_status
      changed_when: false

    - name: Check 4 - Ensure unnecessary services are disabled
      command: >
        sh -c "systemctl list-unit-files | grep enabled | grep -E 'telnet|ftp|rsh|rlogin|rexec' || echo 'No unnecessary services found'"
      register: unnecessary_services
      changed_when: false
      ignore_errors: yes

    - name: Check 5 - Ensure automatic updates are enabled
      shell: |
        grep -E '^APT::Periodic::Update-Package-Lists "1";' /etc/apt/apt.conf.d/20auto-upgrades || echo "APT::Periodic::Update-Package-Lists \"1\";"
      register: auto_updates
      changed_when: false

    - name: Check 6 - Ensure auditd is installed and running
      shell: |
        systemctl is-active auditd || echo "auditd not active"
      register: auditd_status
      changed_when: false

    - name: Check 7 - Ensure SELinux is enabled
      shell: |
        sestatus | grep "SELinux status" | grep "enabled" || echo "SELinux not enabled"
      register: selinux_status
      changed_when: false

    - name: Check 8 - Ensure permissions on sensitive files are correct
      shell: |
        stat -c "%A %n" /etc/passwd /etc/shadow /etc/group | grep -E '^-rw-r--r--|^-rw-------'
      register: file_permissions
      changed_when: false

    - name: Check 9 - Ensure cron is restricted to authorized users
      shell: |
        ls -l /etc/cron.allow /etc/cron.deny || echo "cron not restricted"
      register: cron_restriction
      changed_when: false

    - name: Check 10 - Ensure NTP is configured
      shell: |
        ntpq -p || echo "NTP not configured"
      register: ntp_status
      changed_when: false

    - name: Generate the HTML Report from the Template
      template:
        src: /app/hardening_report_template2.j2
        dest: "/app/{{ inventory_hostname }}_{{ ansible_date_time.iso8601 }}_report.html"
